# Generated by Django 3.2.16 on 2023-02-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='donor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='check', max_length=255),
        ),
    ]
