# Generated by Django 3.2.16 on 2023-02-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230222_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorName', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
