# Generated by Django 3.2.16 on 2023-02-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_paytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayTest',
        ),
    ]
