# Generated by Django 4.1.7 on 2023-08-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sponsorship_payment_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='payment_interval',
            field=models.IntegerField(choices=[(1, 'Monthly'), (3, 'Quarterly'), (6, 'Biannual'), (12, 'Yearly')], default='Monthly'),
        ),
    ]
