# Generated by Django 3.2.16 on 2023-02-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230228_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='sponsor_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_name',
        ),
    ]
