# Generated by Django 3.2.16 on 2023-03-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230306_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sponsor',
            field=models.ManyToManyField(to='home.Donor'),
        ),
    ]
