# Generated by Django 3.2.16 on 2023-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
