# Generated by Django 3.2.16 on 2023-03-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
