# Generated by Django 3.2.16 on 2023-03-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_payment_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='purpose',
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
