# Generated by Django 4.1.7 on 2023-04-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20230322_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duration',
            field=models.IntegerField(default=None),
        ),
    ]
